image: java:11

stages:
  - build
  - package

variables:
  DOCKER_IMAGE_NAME: registry.gitlab.com/jgoldverg/transfer-service
  APP_PORT: 8092
  DOCKER_DRIVER: overlay
  APP_NAME: Transfer Service
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

##Build the project
maven-build:
  image: maven:3-jdk-11
  stage: build
  script: "mvn clean package -DskipTests"
  artifacts:
    paths:
      - target/*.jar

#Run Docker build and push it to the Gitlab Registry
docker-build:
  stage: package
  script:
  - docker build -t registry.gitlab.com/onedatashare/transfer-service .
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker push registry.gitlab.com/onedatashare/transfer-service
