image: docker:latest

stages:
  - test
  - build
  - package

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  DOCKER_IMAGE_NAME: registry.gitlab.com/jgoldverg/Transfer-Service
  APP_PORT: 8092
  DOCKER_DRIVER: overlay
  APP_NAME: Transfer Service
  IMAGE_TAG: $CI_REGISTRY_IMAGE:latest

services:
  - docker:dind

before_script:
  - chmod +x mvnw

#Run maven tests
maven-test:
  image: maven:3-jdk-8
  stage: test
  script:
    - mvn clean test
  artifacts:
    paths:
      - target/

#Build the project
maven-build:
  image: maven:3-jdk-8
  stage: build
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/
 
#Run Docker build and push it to the Gitlab Registry
docker-build:
  stage: package
  script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker build -t $DOCKER_IMAGE_NAME registry.gitlab.com/jgoldverg/Transfer-Service .
  - docker push $IMAGE_TAG
