name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run:
          sudo docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false  # Do not push in this step
          tags: onedatashare/transfer_service:latest

      - name: Create a file
        run: cat "" > /tmp/image/docker-image

      - name: Cache Docker Image
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: /tmp/image
          overwrite: true
  
  push-to-dockerhub:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Restore Cached Docker Image
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: /tmp/image
    
      - name: Push to DockerHub
        run: |
          sudo docker load -i /var/lib/docker/image/docker-image
          sudo docker push onedatashare/transfer_service:latest

  push-to-ecr:
    runs-on: ubuntu-latest
    needs: push-to-dockerhub
    steps:
      - name: Setup AWS ECR Details
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Login to Amazon ECR
        id: login-pf-aws-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Build and push the tagged docker image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
          ECR_REPOSITORY: onedatashare/transfer_service
          IMAGE_TAG: latest
        run: |
          docker pull onedatashare/transfer_service:latest
          docker tag onedatashare/transfer_service:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
