name: Docker Image CI

on:
  push:
    branches:
      - master
      - 'refs/tags/*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAG_NAME: ""
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Extract Tag Name
        run: |
          TAG_NAME=$(echo ${{ github.ref }} | sed 's|refs/tags/||')
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
      - name: Debug Tag Name
        run: echo "TAG_NAME=${TAG_NAME}"
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run:
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build and push dockerhub
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: onedatashare/transfer_service:${TAG_NAME}

  push-to-ecr:
    needs: build
    runs-on: ubuntu-latest
    env:
      TAG_NAME: ${{ needs.build.outputs.TAG_NAME }}
    steps:
      - name: Setup AWS ECR Details
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Login to Amazon ECR
        id: login-pf-aws-ecr
        uses: aws-actions/amazon-ecr-login@v2
        
      - name: Build and push the tagged docker image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
          ECR_REPOSITORY: onedatashare/transfer_service
        run: |
          docker pull onedatashare/transfer_service:${TAG_NAME}
          docker tag onedatashare/transfer_service:${TAG_NAME} $ECR_REGISTRY/$ECR_REPOSITORY:${TAG_NAME}
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${TAG_NAME}
